// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expression struct {
	ID          int32              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	Expression  string             `json:"expression"`
	Result      float32            `json:"result"`
	NumOperands int32              `json:"num_operands"`
	Difficulty  int32              `json:"difficulty"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
